sonar.organization=alejandra-cabrera21
sonar.projectKey=Alejandra-Cabrera21_proyectoo1
sonar.sources=backend,docs
sonar.exclusions=**/node_modules/**,**/Chart.js,**/package-lock.json,**/historial.json
sonar.sourceEncoding=UTF-8
